import { mkdir, readdir, rm, writeFile } from 'node:fs/promises';
import { basename, dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { type PngPage, pngPageFileName } from './entities';

/*
 * Reviewer aid, generated by `visualRegression.test.ts`:
 *
 *   pnpm exec vitest run src/visual
 *   open dist-visual/index.html
 */

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), '..', '..');

/** `dist*` is already gitignored, so contact sheets never enter a commit. */
const CONTACT_SHEET_DIR = join(REPO_ROOT, 'dist-visual');

const DIFF_SUBDIRECTORY = 'diff';

export type ContactSheetPaths = {
  readonly directory: string;
  readonly diffDir: string;
};

/**
 * Give one fixture an empty diff directory to write into.
 *
 * A leftover diff from a previous run is worse than no diff at all, because a
 * reviewer cannot tell the two apart. Only the diff directory is emptied: the
 * fixture directory itself is left in place and its page images are replaced by
 * {@link writeContactSheet}, so a second run of the suite overwrites rather than
 * deleting a directory another run may be writing into.
 */
export const prepareContactSheetDir = async (
  name: string,
  outputDir: string = CONTACT_SHEET_DIR,
): Promise<ContactSheetPaths> => {
  const directory = join(outputDir, name);
  const diffDir = join(directory, DIFF_SUBDIRECTORY);
  await rm(diffDir, { recursive: true, force: true });
  // The diff directory is created here rather than lazily by the comparator, so
  // a comparison can never fail because its debugging artefact had nowhere to go.
  await mkdir(diffDir, { recursive: true });
  return { directory, diffDir };
};

export type ContactSheetColumn = {
  readonly label: string;
  readonly pages: ReadonlyArray<PngPage>;
  /** Shown under the column heading, for example a baseline result reason. */
  readonly note?: string;
};

export type WriteContactSheetOptions = {
  readonly name: string;
  readonly columns: ReadonlyArray<ContactSheetColumn>;
  readonly diffDir?: string;
  readonly diffLabel?: string;
  /** Pages beyond this are reported as not compared rather than as identical. */
  readonly diffPageCount?: number;
  readonly outputDir?: string;
  readonly summary?: ReadonlyArray<string>;
};

const escapeHtml = (value: string): string =>
  value
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');

const STYLE = `
  :root { color-scheme: light dark; }
  body { font: 13px/1.5 ui-sans-serif, system-ui, sans-serif; margin: 2rem; }
  h1 { font-size: 1.4rem; margin-bottom: 0.25rem; }
  ul.summary { margin: 0 0 1.5rem; padding-left: 1.2rem; color: #555; }
  table { border-collapse: collapse; width: 100%; }
  th, td { border: 1px solid #bbb; padding: 0.5rem; vertical-align: top; }
  th { position: sticky; top: 0; background: #fff; text-align: left; }
  th small { display: block; font-weight: normal; color: #666; }
  td.page-number { width: 3rem; text-align: right; font-variant-numeric: tabular-nums; }
  img { width: 100%; height: auto; display: block; background: #fff; border: 1px solid #eee; }
  .missing { color: #a00; font-style: italic; }
`;

/**
 * Write a reviewer aid: one row per page, one column per target, so a layout
 * regression can be seen rather than inferred from a mismatch ratio.
 *
 * Images are written as files next to the page rather than inlined as data
 * URLs: a three target, three page fixture inlines to well over a megabyte of
 * base64, which is slow to open and impossible to diff.
 */
export const writeContactSheet = async ({
  name,
  columns,
  diffDir,
  diffLabel,
  diffPageCount,
  outputDir = CONTACT_SHEET_DIR,
  summary = [],
}: WriteContactSheetOptions): Promise<string> => {
  const directory = join(outputDir, name);
  await mkdir(directory, { recursive: true });

  // Drop the previous run's page images first: a document that lost a page
  // would otherwise leave an orphan in the sheet that reads as current.
  const existing = await readdir(directory).catch(() => []);
  for (const file of existing) {
    if (columns.some(({ label }) => file.startsWith(`${label}-page-`))) {
      await rm(join(directory, file), { force: true });
    }
  }

  const written = await Promise.all(
    columns.map(async ({ label, pages }) =>
      Promise.all(
        pages.map(async (page, index) => {
          const fileName = pngPageFileName(label, index);
          await writeFile(join(directory, fileName), page.buffer);
          return fileName;
        }),
      ),
    ),
  );

  const diffFiles = diffDir
    ? (await readdir(diffDir).catch(() => []))
        .filter((file) => file.endsWith('.png'))
        .sort()
    : [];
  const diffByPage = new Map<number, string>(
    diffFiles.map((file) => {
      const matched = /-page-(\d+)\.png$/.exec(file);
      return [matched ? Number(matched[1]) : 0, file];
    }),
  );

  const pageCount = Math.max(
    0,
    ...columns.map(({ pages }) => pages.length),
    ...[...diffByPage.keys()],
  );

  const headings = [
    '<th class="page-number">#</th>',
    ...columns.map(
      ({ label, pages, note }) =>
        `<th>${escapeHtml(label)}<small>${pages.length} page(s)${
          note ? ` &middot; ${escapeHtml(note)}` : ''
        }</small></th>`,
    ),
    diffDir
      ? `<th>diff<small>${escapeHtml(diffLabel ?? 'cross target')}</small></th>`
      : undefined,
  ].filter((heading): heading is string => heading !== undefined);

  const rows = Array.from({ length: pageCount }, (_, index) => {
    const cells = columns.map(({ label }, columnIndex) => {
      const fileName = written[columnIndex][index];
      return fileName
        ? `<td><img loading="lazy" src="${name}/${escapeHtml(fileName)}" alt="${escapeHtml(
            `${label} page ${index + 1}`,
          )}"></td>`
        : '<td class="missing">no page</td>';
    });
    const diffFile = diffByPage.get(index + 1);
    const compared = diffPageCount === undefined || index < diffPageCount;
    const diffCell = diffDir
      ? diffFile
        ? `<td><img loading="lazy" src="${name}/${DIFF_SUBDIRECTORY}/${escapeHtml(diffFile)}" alt="diff page ${index + 1}"></td>`
        : `<td>${compared ? 'identical' : 'not compared'}</td>`
      : undefined;
    return `<tr><td class="page-number">${index + 1}</td>${cells.join('')}${diffCell ?? ''}</tr>`;
  });

  const htmlPath = join(outputDir, `${name}.html`);
  await writeFile(
    htmlPath,
    `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>${escapeHtml(name)} contact sheet</title>
<style>${STYLE}</style>
</head>
<body>
<h1>${escapeHtml(name)}</h1>
<ul class="summary">${summary.map((line) => `<li>${escapeHtml(line)}</li>`).join('')}</ul>
<table>
<thead><tr>${headings.join('')}</tr></thead>
<tbody>${rows.join('\n')}</tbody>
</table>
</body>
</html>
`,
    'utf-8',
  );
  return htmlPath;
};

/** A table of contents so a reviewer can open one file and reach every sheet. */
export const writeContactSheetIndex = async (
  htmlPaths: ReadonlyArray<string>,
  outputDir: string = CONTACT_SHEET_DIR,
): Promise<string> => {
  const indexPath = join(outputDir, 'index.html');
  await mkdir(outputDir, { recursive: true });
  await writeFile(
    indexPath,
    `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>matti-docs visual contact sheets</title>
<style>${STYLE}</style>
</head>
<body>
<h1>Visual contact sheets</h1>
<ul>${htmlPaths
      .map(
        (htmlPath) =>
          `<li><a href="${escapeHtml(basename(htmlPath))}">${escapeHtml(
            basename(htmlPath, '.html'),
          )}</a></li>`,
      )
      .join('')}</ul>
</body>
</html>
`,
    'utf-8',
  );
  return indexPath;
};
