import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { createNodeDriver } from '@pandacss/dev/node';
import postcss from 'postcss';

const ROOT_DIR = join(dirname(fileURLToPath(import.meta.url)), '..');

/** The compiled stylesheets, as a string module. */
export const STYLES_PATH = 'src/generated/styles.ts';

const LAYER_ORDER = '@layer reset, base, tokens, recipes, utilities;';

/**
 * Panda's reset gives `:host` the page's global font and line height. The
 * page element's content inherits those from the element instead, so the rule
 * is removed, as matti-kit's shadow stylesheet build removes it.
 */
const HOST_RESET_RULE = /^ {2}html, :host \{\n(?: {4}.*\n)*? {2}\}\n/m;

type PandaDiagnostic = { readonly code: string; readonly message: string };

/**
 * Compiles the `globalCss` (and, when the config enables it, the preflight) of
 * `configPath`, relative to the package root, the way matti-kit's shadow
 * stylesheet build does: `createNodeDriver`, `getLayerCss`,
 * `stripLayerOrderStatements`. Any Panda diagnostic fails the build rather
 * than shipping silently broken CSS.
 */
export const compileLayerCss = async (configPath: string): Promise<string> => {
  const { compiler } = await createNodeDriver({ cwd: ROOT_DIR, configPath });
  const layers = compiler.getLayerCss({ layers: ['reset', 'base'] });
  const diagnostics: ReadonlyArray<PandaDiagnostic> = layers.diagnostics;
  if (diagnostics.length > 0) {
    throw new Error(
      `Panda reported ${diagnostics.length} diagnostic(s) in ${configPath}:\n${diagnostics
        .map(({ code, message }) => `  ${code}: ${message}`)
        .join('\n')}`,
    );
  }
  return compiler.stripLayerOrderStatements(layers.css);
};

/** Panda's signature, which would otherwise be adopted into every document. */
const removeSignature = (root: postcss.Root) => {
  root.walkRules(':root', (rule) => {
    if (
      rule.nodes.every(
        (node) => node.type === 'decl' && node.prop === '--made-with-panda',
      )
    ) {
      rule.remove();
    }
  });
};

/**
 * Rules inside a cascade layer lose to every unlayered rule of a host page,
 * whatever their specificity, so the sheets the library adopts into the light
 * DOM carry none. `stripLayerOrderStatements` only removes the `@layer a, b;`
 * statement; the blocks themselves are unwrapped here.
 */
export const unwrapLayers = (css: string): string => {
  const root = postcss.parse(css);
  root.walkAtRules('layer', (atRule) => {
    if (atRule.nodes) {
      atRule.replaceWith(atRule.nodes);
    } else {
      atRule.remove();
    }
  });
  removeSignature(root);
  return root.toString().trim();
};

/**
 * A shadow root holds nothing but the library's own sheet, so its layers are
 * kept, declared in matti-kit's order, and preflight's `html, :host` rule is
 * dropped.
 */
export const toShadowCss = (css: string): string => {
  if (!HOST_RESET_RULE.test(css)) {
    throw new Error(
      "Panda's reset no longer has the expected `html, :host` rule; update HOST_RESET_RULE in scripts/buildStyles.ts.",
    );
  }
  const root = postcss.parse(css.replace(HOST_RESET_RULE, ''));
  removeSignature(root);
  return `${LAYER_ORDER}\n${root.toString().trim()}`;
};

export const compileStyles = async () => ({
  NEUTRAL_STYLES: unwrapLayers(
    await compileLayerCss('panda.neutral.config.ts'),
  ),
  CONTENT_STYLES_TEMPLATE: unwrapLayers(
    await compileLayerCss('panda.config.ts'),
  ),
  PAGE_SHADOW_STYLES: toShadowCss(
    await compileLayerCss('panda.shadow.config.ts'),
  ),
});

/**
 * Writes {@link STYLES_PATH}. The file is generated rather than committed, and
 * a string module rather than `.css` files because the `?source` bundle
 * `htmlToScript` inlines cannot import CSS.
 */
export const buildStyles = async (): Promise<{ changed: boolean }> => {
  const styles = await compileStyles();
  const source = [
    '// Generated by scripts/buildStyles.ts from the panda.*config.ts files. Do not edit.',
    ...Object.entries(styles).map(
      ([name, css]) => `export const ${name} = ${JSON.stringify(css)};`,
    ),
    '',
  ].join('\n');
  const path = join(ROOT_DIR, STYLES_PATH);
  const changed = !existsSync(path) || readFileSync(path, 'utf8') !== source;
  if (changed) {
    mkdirSync(dirname(path), { recursive: true });
    writeFileSync(path, source);
  }
  return { changed };
};

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { changed } = await buildStyles();
  console.info(`${STYLES_PATH} ${changed ? 'written' : 'already up to date'}.`);
}
